USERS_URL = 'https://showoff-rails-react-production.herokuapp.com/api/v1/users'.freeze
VISIBLE_WIDGETS_URL = 'https://showoff-rails-react-production.herokuapp.com/api/v1/widgets/visible?client_id='.freeze
MY_USER_URL = 'https://showoff-rails-react-production.herokuapp.com/api/v1/users/me'.freeze
MY_WIDGETS_URL = 'https://showoff-rails-react-production.herokuapp.com/api/v1/users/me/widgets'.freeze
USER_WIDGETS = 'https://showoff-rails-react-production.herokuapp.com/api/v1/users/'.freeze
MY_USER_WIDGETS = 'https://showoff-rails-react-production.herokuapp.com/api/v1/users/me/widgets?'.freeze
WIDGETS_URL = 'https://showoff-rails-react-production.herokuapp.com/api/v1/widgets'.freeze
REFRESH_TOKEN = 'https://showoff-rails-react-production.herokuapp.com/oauth/token'.freeze
WIDGET_URL = 'https://showoff-rails-react-production.herokuapp.com/api/v1/widgets/'.freeze
